version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_gorm
    ports:
      - "5433:5432" # 5432 udah kepake
    environment:
      POSTGRES_DB: mahasiswa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docket-entrypoint-initdb.d/init.sql
